// import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import localFont from 'next/font/local';
import Head from "next/head";

// const inter = Inter({ subsets: ["latin"] });


// font-family: 'NeueHaasGrotesk', sans-serif;
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

//configurando la fuente local
const neueHaasGrotesk = localFont({
  src: '../../public/fonts/NeueHaasGrotesk.woff2',
  weight: 'normal',
  style: 'normal',
  display: 'swap',
  variable: '--font-neue-haas-grotesk'
});




export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={neueHaasGrotesk.variable}>
        <NavBar />

        {children}
      </body>
    </html>
  );
}
