"use client";

 import { Urbanist } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
// import localFont from 'next/font/local';
import Head from "next/head";
import { CartProvider } from "@/context/CartContext";
import { UseLovedProductsProvider } from "@/context/UseLovedProducts";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import Footer from "./components/Footer";

const urbanist = Urbanist({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="es">
        <Head>
          <title>IndumentaryBrix</title>
        </Head>
        <body className={`${urbanist.className} flex flex-col min-h-screen`}>
          <CartProvider>
            <UseLovedProductsProvider>
              <NavBar />
              <main className="flex-grow">{children}</main>
              <Footer />
            </UseLovedProductsProvider>
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}





























//CODIGO FUNCIONANDO
// "use client";

//  import { Urbanist } from "next/font/google";
// import "./globals.css";
// import NavBar from "./components/NavBar";
// import localFont from 'next/font/local';
// import Head from "next/head";
// import { CartProvider } from "@/context/CartContext";



// import {
//   ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton
// } from '@clerk/nextjs'

// // const inter = Inter({ subsets: ["latin"] });


// // font-family: 'NeueHaasGrotesk', sans-serif;
// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// //configurando la fuente local
// // const neueHaasGrotesk = localFont({
// //   src: '../../public/fonts/NeueHaasGrotesk.woff2',
// //   weight: 'normal',
// //   style: 'normal',
// //   display: 'swap',
// //   variable: '--font-neue-haas-grotesk'
// // });

// const urbanist = Urbanist({ subsets: ["latin"] });





// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//     <html lang="es">
//       <Head>
//         <title>Brix Indumentary</title>
//       </Head>
//       <body className={urbanist.className}>
        
//         <CartProvider>
//           <NavBar/>
//           {children}
//         </CartProvider>
        
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }
